name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Test path
      run: pwd
    - name: Restore dependencies
      run: dotnet restore  ..\..\GitHubActionsForDotNET\
    - name: Build
      run: dotnet build --no-restore ..\..\GitHubActionsForDotNET\
    - name: Test
      run: dotnet test --no-build --verbosity normal ..\..\GitHubActionsForDotNET\
